#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2cm, left: 1.5cm, right: 1.5cm),
  header: context {
    if counter(page).get().first() > 1 [
      #align(center)[#text(size: 8pt, fill: luma(120))[A278299: Smallest Complete Polyomino Coloring]]
    ]
  },
  footer: context {
    let current = counter(page).get().first()
    let total = counter(page).final().first()
    align(center)[#text(size: 8pt, fill: luma(120))[Page #current of #total]]
  },
)
#set text(font: "New Computer Modern", size: 9pt)

#align(center)[
  #text(size: 16pt, weight: "bold")[A278299: Smallest Complete Polyomino Coloring]
  #v(0.3em)
  #text(size: 10pt)[Minimum cells in a polyomino with $n$-coloring where every color pair shares an edge]
  #v(0.2em)
  #text(size: 10pt)[Proved: $a(12) = 40$, $a(13) = 46$, $a(14) = 56$, $a(15) = 61$, $a(16) = 69$, $a(17) = 77$, $a(18) = 90$]
  #v(0.2em)
  #text(size: 8pt, style: "italic")[Computed by Peter Exley, March 2026]
]
#v(0.5em)
#line(length: 100%, stroke: 0.5pt)
#v(0.3em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(12) = 40$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[5 \u{00D7} 8 bounding box, 66 color pairs. Edge bound: 65 < 66]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 8,
  rows: (7mm,) * 5,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(13) = 46$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[7 \u{00D7} 7 bounding box, 78 color pairs. Edge bound: 76 < 78]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 7,
  rows: (7mm,) * 7,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell()[],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell()[],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell()[],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(14) = 56$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[7 \u{00D7} 8 bounding box, 91 color pairs. Contact bound: 12 < 13]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 8,
  rows: (7mm,) * 7,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(15) = 61$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[7 \u{00D7} 9 bounding box, 105 color pairs. Edge bound: 104 < 105]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 9,
  rows: (7mm,) * 7,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell()[],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell()[],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(16) = 69$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[8 \u{00D7} 10 bounding box, 120 color pairs. Edge bound: 119 < 120]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 10,
  rows: (7mm,) * 8,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell()[],
  table.cell()[],
  table.cell()[],
  table.cell()[],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell()[],
  table.cell()[],
  table.cell()[],
  table.cell()[],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell()[],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell()[],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell()[],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(17) = 77$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[8 \u{00D7} 10 bounding box, 136 color pairs. Edge bound: 134 < 136]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 10,
  rows: (7mm,) * 8,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell()[],
  table.cell()[],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell()[],
)
]
]
#v(0.5em)
#block(breakable: false, width: 100%)[
#align(center)[
  #text(size: 11pt, weight: "bold")[$a(18) = 90$]#text(size: 8pt, fill: rgb("#27AE60"), weight: "bold")[ \[PROVED\]]
  #h(0.5em)
  #text(size: 8pt)[9 \u{00D7} 10 bounding box, 153 color pairs. Contact bound: 16 < 17]
]
#v(0.2em)
#align(center)[
#table(
  columns: (7mm,) * 10,
  rows: (7mm,) * 9,
  inset: 0pt,
  stroke: none,
  align: center + horizon,
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[R]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#16A085"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[G]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[R]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[J]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[P]],
  table.cell(fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[R]],
  table.cell(fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[E]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[O]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[Q]],
  table.cell(fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[F]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[D]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
  table.cell(fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[C]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[R]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[R]],
  table.cell(fill: rgb("#795548"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[I]],
  table.cell(fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[B]],
  table.cell(fill: rgb("#689F38"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[K]],
  table.cell(fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[L]],
  table.cell(fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[A]],
  table.cell(fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[H]],
  table.cell(fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: black, weight: "bold")[M]],
  table.cell(fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))[#text(size: 7pt, fill: white, weight: "bold")[N]],
)
]
]
#v(0.5em)
#line(length: 100%, stroke: 0.5pt)
#v(0.3em)
#align(center)[#text(size: 9pt, weight: "bold")[Color Legend]]
#v(0.2em)
#align(center)[
#table(
  columns: (auto,) * 7,
  inset: 4pt,
  stroke: none,
  align: center + horizon,
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#E74C3C"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[A=0]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#2980B9"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[B=1]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#27AE60"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[C=2]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#F1C40F"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[D=3]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#8E44AD"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[E=4]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#E67E22"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[F=5]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#16A085"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[G=6]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#E91E63"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[H=7]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#795548"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[I=8]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#607D8B"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[J=9]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#689F38"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[K=10]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#1A237E"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[L=11]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#00BCD4"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[M=12]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#B71C1C"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[N=13]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#FF8A65"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[O=14]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#AD1457"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[P=15]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#BF8C00"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[Q=16]],
  table.cell()[#box(baseline: 25%, width: 5mm, height: 5mm, fill: rgb("#FF5722"), stroke: 0.3pt + luma(80))#h(1pt)#text(size: 7pt)[R=17]],
  table.cell()[],
  table.cell()[],
  table.cell()[],
)
]